#!/usr/bin/with-contenv bash

if [ "${CUDA_ACCELERATION}" = "true" ]; then
    # install pip deps
    apt-get update
    apt-get install --no-install-recommends -y \
        g++ \
        python3-dev \
        python3-venv

    # apply early ml support
    cp /defaults/main.py /app/immich/machine-learning/src/main.py
    # create venv if it does not exist
    if [ ! -d /config/cuda-venv ]; then
        python3 -m venv /config/cuda-venv/
    fi

    # install/update pip packages to /config venv
    source /config/cuda-venv/bin/activate
    pip install -U --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cu117 \
        torch==1.13.1 \
        torchvision==0.14.1
    pip install -U --no-cache-dir \
        coloredlogs \
        fastapi \
        flatbuffers \
        insightface \
        packaging \
        protobuf \
        scikit-learn \
        scipy \
        sentence-transformers \
        sympy \
        transformers \
        uvicorn[standard]
    pip install -U --no-cache-dir --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ \
        ort-nightly-gpu

    # cleanup
    apt-get remove -y --purge \
        g++ \
        python3-dev
    apt-get autoremove -y --purge
    apt-get clean
fi
