#!/usr/bin/with-contenv bash

# check if typesense is set to an external server
[[ "${TYPESENSE_HOST}" != "127.0.0.1" ]] && echo "WARN: Disabling the Typesense service as 'TYPESENSE_HOST' is set externally (${TYPESENSE_HOST})!"

# stop typesense from starting
[[ "${DISABLE_TYPESENSE}" == "true" || "${TYPESENSE_HOST}" != "127.0.0.1" ]] && tail -f /dev/null

exec \
    cd /app/typesense s6-setuidgid abc \
        ./typesense-server \
            --api-key=${TYPESENSE_API_KEY:-xyz} \
            --enable-cors &>/dev/null
