#!/usr/bin/with-contenv bash

# stop typesense from starting
if [ "${DISABLE_TYPESENSE}" == "true" || "${TYPESENSE_HOST}" != "127.0.0.1" ]; then
    tail -f /dev/null
fi

exec \
    cd /app/typesense s6-setuidgid abc \
        ./typesense-server \
            --api-key=${TYPESENSE_API_KEY} \
            --enable-cors &>/dev/null
