#!/usr/bin/with-contenv bash

export HOME=/config

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
        cd /app/immich/web s6-setuidgid abc \
            node build/index.js
