#!/usr/bin/with-contenv bash
# shellcheck shell=bash

lib_path="/usr/lib/$(arch)-linux-gnu/libmimalloc.so.2"
export LD_PRELOAD="$lib_path"

: "${CPU_CORES:="$(/app/immich/server/scripts/get-cpus.sh)"}"
echo "Detected CPU Cores: ${CPU_CORES}"
if [ "${CPU_CORES}" -gt 4 ]; then
    export UV_THREADPOOL_SIZE=${CPU_CORES}
fi

exec \
    cd /app/immich/server s6-setuidgid abc \
        node dist/main microservices || exit
