#!/usr/bin/with-contenv bash
# shellcheck shell=bash

lib_path="/usr/lib/$(arch)-linux-gnu/libmimalloc.so.2"
export IMMICH_WORKERS_INCLUDE="microservices"
export LD_PRELOAD="${lib_path}"

exec \
    cd /app/immich/server s6-setuidgid abc \
        node dist/main || exit
