#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export IMMICH_WORKERS_INCLUDE="microservices"
export LD_PRELOAD="/usr/lib/$(arch)-linux-gnu/libmimalloc.so.3"

exec \
    cd /app/immich/server s6-setuidgid abc \
        node dist/main || exit
