#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# install immich dependencies for test runs
if [[ -n "${TEST_RUN}" ]]; then
    echo "Configuring CI for test run"
    apt-get update &>/dev/null
    apt-get install -y --no-install-recommends \
        postgresql-15 \
        redis-server &>/dev/null

    s6-setuidgid postgres pg_ctlcluster 15 main start
    s6-setuidgid postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';"

    # Install vectors
    curl -o \
        /tmp/vectors.deb -L \
        "https://github.com/tensorchord/pgvecto.rs/releases/download/v0.1.11/vectors-pg15-v0.1.11-$(arch)-unknown-linux-gnu.deb"
    dpkg -i /tmp/vectors.deb

    # Setup vectors
    s6-setuidgid postgres psql -c 'ALTER SYSTEM SET shared_preload_libraries = "vectors.so"'
    sleep 1
    pkill postgres
    sleep 1
    s6-setuidgid postgres pg_ctlcluster 15 main start
    sleep 1
    s6-setuidgid postgres psql -c "CREATE EXTENSION vectors;"

    s6-setuidgid abc redis-server --dir /config/ &>/dev/null &

    echo "PostgreSQL/Redis started"
fi
