#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# map disable variables to immich variables
[[ "${DISABLE_MACHINE_LEARNING}" == "true" ]] && export IMMICH_MACHINE_LEARNING_ENABLED=false

lib_path="/usr/lib/$(arch)-linux-gnu/libmimalloc.so.2"
export LD_PRELOAD="${lib_path}"
export IMMICH_WORKERS_INCLUDE="api"

exec \
    s6-notifyoncheck -d -n 300 -w 5000 -c "nc -z localhost ${IMMICH_PORT}" \
        cd /app/immich/server s6-setuidgid abc \
            node dist/main
