#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/machine-learning \
    /import \
    /photos \
    /run/immich

# permissions
find /photos \( ! -user abc -o ! -group abc \) -exec lsiown abc:abc {} \;
find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +
lsiown -R abc:abc \
    /config \
    /run/immich \
    /usr/src/resources
