#!/usr/bin/with-contenv bash

if [ "${MACHINE_LEANRNING_ENABLED}" == "false" ]; then
    tail -f /dev/null;
else
    export HOME=/config
    exec \
        cd /app/immich/machine-learning s6-setuidgid abc \
            gunicorn src.main:server
fi