#!/usr/bin/with-contenv bash

# stop machine learning from starting
if [ "${DISABLE_MACHINE_LEANRNING}" == "true" ]; then
    tail -f /dev/null
fi

if [ "$ML_CUDA" = "true" ]; then
    apt-get update
    apt-get install -y python3-venv python3-numpy python3-dev g++ 
    sed -i 's/pipeline(model=model, task=task)/pipeline(model=model, task=task, device=0)/' /app/immich/machine-learning/src/main.py
    if [ ! -d "/config/cuda" ]; then
        python3 -m venv /config/cuda/
        source /config/cuda/bin/activate
        pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchtext==0.14.1 torchaudio==0.13.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu117
    else
        source /config/cuda/bin/activate
    fi
        pip install -U --no-cache-dir \
            coloredlogs \
            fastapi \
            flatbuffers \
            insightface \
            nltk \
            packaging \
            pillow \
            protobuf \
            sympy \
            scikit-learn \
            scipy \
            sentence-transformers \
            sentencepiece \
            tqdm \
            transformers \
            uvicorn[standard]
        pip install -U --no-cache-dir --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ \
            ort-nightly
fi

export HOME=/tmp
exec \
    cd /app/immich/machine-learning s6-setuidgid abc \
        python3 src/main.py
