#!/usr/bin/with-contenv bash

# stop machine learning from starting
if [ "${DISABLE_MACHINE_LEANRNING}" == "true" ]; then
    tail -f /dev/null
fi

export HOME=/home
exec \
    cd /app/immich/machine-learning s6-setuidgid abc \
        python3 main.py
