#!/usr/bin/with-contenv python3

import os
import sys

# Check if CI_RUN variable is set
if "CI_RUN" not in os.environ:
    from sentence_transformers import SentenceTransformer
    from transformers import pipeline

    # Print message before downloading models
    print("Initialising caches... This may take a while! (errors can be ignored)")

    # Disable output
    sys.stdout = open(os.devnull, "w")
    sys.stderr = open(os.devnull, "w")

    # Create the cache directory if it doesn't exist
    cache_dir = os.environ.get("TRANSFORMERS_CACHE", "/config/transformers")
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)

    # install the models in /cache
    classification_model = pipeline(
        task="image-classification", model="microsoft/resnet-50")
    object_model = pipeline(task="object-detection", model="hustvl/yolos-tiny")
    clip_model = SentenceTransformer("clip-ViT-B-32")
