---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Mod Cache

on:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  go-cache:
    name: Go Module Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Download Go Modules
        run: go mod download
