---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: $/.github/workflows/build.yaml
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    with:
      variant: all
      release: false

  status:
    if: ${{ !cancelled() }}
    name: Build Success
    needs: build
    runs-on: ubuntu-26.04
    permissions: {}
    steps:
      - name: Check Build Result
        env:
          RESULT: ${{ needs.build.result }}
        run: test "$RESULT" = success
