---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build Matrix
        uses: ./.github/actions/bake-matrix
        id: matrix
        with:
          variants: '["main","noml","cuda","openvino"]'

  build:
    name: ${{ matrix.variant }} / Build and Test (${{ matrix.platform }})
    needs:
      - plan
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.plan.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          experimental: true
          install_args: --locked

      - name: Restore Go Modules
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build Local Image
        run: |-
          docker buildx bake \
            --no-cache \
            --file docker-bake.hcl \
            --set image-${{ matrix.variant }}-local.platform=${{ matrix.platform }} \
            --load \
            image-${{ matrix.variant }}-local

      - name: Run Tests
        env:
          TEST_IMAGE: immich:local-${{ matrix.variant }}
          VARIANT: ${{ matrix.variant }}
        run: |-
          go test -v -timeout 15m ./tests/...

  status:
    if: ${{ !cancelled() }}
    name: Build Success
    needs:
      - plan
      - build
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All builds passed"
