---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - docker-bake.hcl
      - "root/**"
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        options:
          - main
          - noml
          - cuda
          - openvino
          - all
        default: all
      no-cache:
        type: boolean
        description: Build without layer cache
        default: false
      release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: $/.github/workflows/build.yaml
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      variant: ${{ github.event_name == 'workflow_dispatch' && inputs.variant || 'all' }}
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || github.event_name == 'push' }}
      no-cache: ${{ github.event_name == 'workflow_dispatch' && inputs.no-cache }}

  status:
    if: ${{ !cancelled() }}
    name: Release Success
    needs: build
    runs-on: ubuntu-26.04
    permissions: {}
    steps:
      - name: Check Build Result
        env:
          RESULT: ${{ needs.build.result }}
        run: test "$RESULT" = success
