---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .renovaterc.json5
      - .renovate/**.json5
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ".github"
          permission-actions: write

      - name: Run Renovate
        id: dispatch
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          RUN_URL=$(gh workflow run renovate.yaml \
            --repo "${{ github.repository_owner }}/.github" \
            --ref main \
            --field "autodiscoverFilter=${REPO_NAME}")
          echo "run_id=${RUN_URL##*/}" >> "$GITHUB_OUTPUT"

      - name: Await Renovate Completion
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          RUN_ID: ${{ steps.dispatch.outputs.run_id }}
        run: |
          gh run watch \
            --repo "${{ github.repository_owner }}/.github" \
            "${RUN_ID}" \
            --exit-status

      - name: Renovate Output
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          RUN_ID: ${{ steps.dispatch.outputs.run_id }}
        run: |
          gh run view \
            --repo "${{ github.repository_owner }}/.github" \
            --log "${RUN_ID}"
